package io.github.xfacthd.microredstone.util;

import io.github.xfacthd.microredstone.common.circuit.connection.Connection;
import io.github.xfacthd.microredstone.common.circuit.connection.Port;
import io.github.xfacthd.microredstone.common.circuit.connection.PortDir;
import io.github.xfacthd.microredstone.common.circuit.connection.Wire;
import io.github.xfacthd.microredstone.common.circuit.connection.WireType;
import io.github.xfacthd.microredstone.common.circuit.prototype.CompoundPrototypeNode;
import io.github.xfacthd.microredstone.common.circuit.prototype.ConverterPrototypeNode;
import io.github.xfacthd.microredstone.common.circuit.prototype.PrimitivePrototypeNode;

public final class ComplexTestCircuits
{
    public static CompoundPrototypeNode bcdTo7SegDecoder()
    {
        TestBuilder builder = new TestBuilder();

        Wire wireIn = builder.addWire(WireType.BUNDLED);
        Wire wireInA = builder.addWire(WireType.SINGLE);
        Wire wireInNA = builder.addWire(WireType.SINGLE);
        Wire wireInB = builder.addWire(WireType.SINGLE);
        Wire wireInNB = builder.addWire(WireType.SINGLE);
        Wire wireInC = builder.addWire(WireType.SINGLE);
        Wire wireInNC = builder.addWire(WireType.SINGLE);
        Wire wireInD = builder.addWire(WireType.SINGLE);
        Wire wireOutNANC = builder.addWire(WireType.SINGLE);
        Wire wireOutAC = builder.addWire(WireType.SINGLE);
        Wire wireOutNAC = builder.addWire(WireType.SINGLE);
        Wire wireOutAB = builder.addWire(WireType.SINGLE);
        Wire wireOutNANB = builder.addWire(WireType.SINGLE);
        Wire wireOutNAB = builder.addWire(WireType.SINGLE);
        Wire wireOutANBC = builder.addWire(WireType.SINGLE);
        Wire wireOutBNC = builder.addWire(WireType.SINGLE);
        Wire wireOutNBC = builder.addWire(WireType.SINGLE);
        Wire wireOutA = builder.addWire(WireType.SINGLE);
        Wire wireOutAInter = builder.addWire(WireType.SINGLE);
        Wire wireOutB = builder.addWire(WireType.SINGLE);
        Wire wireOutC = builder.addWire(WireType.SINGLE);
        Wire wireOutD = builder.addWire(WireType.SINGLE);
        Wire wireOutDInter = builder.addWire(WireType.SINGLE);
        Wire wireOutE = builder.addWire(WireType.SINGLE);
        Wire wireOutF = builder.addWire(WireType.SINGLE);
        Wire wireOutFInter = builder.addWire(WireType.SINGLE);
        Wire wireOutG = builder.addWire(WireType.SINGLE);
        Wire wireOutGInter = builder.addWire(WireType.SINGLE);
        Wire wireOut = builder.addWire(WireType.BUNDLED);

        Connection conIn = builder.addConnection(Port.LEFT, WireType.BUNDLED, PortDir.INPUT);
        conIn.connect(wireIn);
        Connection conOut = builder.addConnection(Port.RIGHT, WireType.BUNDLED, PortDir.OUTPUT);
        conOut.connect(wireOut);

        ConverterPrototypeNode unpackA = builder.addNode(new ConverterPrototypeNode(ConverterPrototypeNode.Type.UNPACK));
        unpackA.setBitIndex(0);
        unpackA.setConnection(Port.LEFT, wireIn, true);
        unpackA.setConnection(Port.RIGHT, wireInA, true);
        ConverterPrototypeNode unpackB = builder.addNode(new ConverterPrototypeNode(ConverterPrototypeNode.Type.UNPACK));
        unpackB.setBitIndex(1);
        unpackB.setConnection(Port.LEFT, wireIn, true);
        unpackB.setConnection(Port.RIGHT, wireInB, true);
        ConverterPrototypeNode unpackC = builder.addNode(new ConverterPrototypeNode(ConverterPrototypeNode.Type.UNPACK));
        unpackC.setBitIndex(2);
        unpackC.setConnection(Port.LEFT, wireIn, true);
        unpackC.setConnection(Port.RIGHT, wireInC, true);
        ConverterPrototypeNode unpackD = builder.addNode(new ConverterPrototypeNode(ConverterPrototypeNode.Type.UNPACK));
        unpackD.setBitIndex(3);
        unpackD.setConnection(Port.LEFT, wireIn, true);
        unpackD.setConnection(Port.RIGHT, wireInD, true);

        PrimitivePrototypeNode notA = builder.addNode(new PrimitivePrototypeNode(PrimitivePrototypeNode.Type.NOT, 1, WireType.SINGLE));
        notA.setConnection(Port.LEFT, wireInA, true);
        notA.setConnection(Port.RIGHT, wireInNA, true);
        PrimitivePrototypeNode notB = builder.addNode(new PrimitivePrototypeNode(PrimitivePrototypeNode.Type.NOT, 1, WireType.SINGLE));
        notB.setConnection(Port.LEFT, wireInB, true);
        notB.setConnection(Port.RIGHT, wireInNB, true);
        PrimitivePrototypeNode notC = builder.addNode(new PrimitivePrototypeNode(PrimitivePrototypeNode.Type.NOT, 1, WireType.SINGLE));
        notC.setConnection(Port.LEFT, wireInC, true);
        notC.setConnection(Port.RIGHT, wireInNC, true);

        PrimitivePrototypeNode andNANC = builder.addNode(new PrimitivePrototypeNode(PrimitivePrototypeNode.Type.AND, 2, WireType.SINGLE));
        andNANC.setConnection(Port.UP, wireInNA, true);
        andNANC.setConnection(Port.DOWN, wireInNC, true);
        andNANC.setConnection(Port.RIGHT, wireOutNANC, true);
        PrimitivePrototypeNode andAC = builder.addNode(new PrimitivePrototypeNode(PrimitivePrototypeNode.Type.AND, 2, WireType.SINGLE));
        andAC.setConnection(Port.UP, wireInA, true);
        andAC.setConnection(Port.DOWN, wireInC, true);
        andAC.setConnection(Port.RIGHT, wireOutAC, true);
        PrimitivePrototypeNode andNAC = builder.addNode(new PrimitivePrototypeNode(PrimitivePrototypeNode.Type.AND, 2, WireType.SINGLE));
        andNAC.setConnection(Port.UP, wireInNA, true);
        andNAC.setConnection(Port.DOWN, wireInC, true);
        andNAC.setConnection(Port.RIGHT, wireOutNAC, true);
        PrimitivePrototypeNode andAB = builder.addNode(new PrimitivePrototypeNode(PrimitivePrototypeNode.Type.AND, 2, WireType.SINGLE));
        andAB.setConnection(Port.UP, wireInA, true);
        andAB.setConnection(Port.DOWN, wireInB, true);
        andAB.setConnection(Port.RIGHT, wireOutAB, true);
        PrimitivePrototypeNode andNANB = builder.addNode(new PrimitivePrototypeNode(PrimitivePrototypeNode.Type.AND, 2, WireType.SINGLE));
        andNANB.setConnection(Port.UP, wireInNA, true);
        andNANB.setConnection(Port.DOWN, wireInNB, true);
        andNANB.setConnection(Port.RIGHT, wireOutNANB, true);
        PrimitivePrototypeNode andNAB = builder.addNode(new PrimitivePrototypeNode(PrimitivePrototypeNode.Type.AND, 2, WireType.SINGLE));
        andNAB.setConnection(Port.UP, wireInNA, true);
        andNAB.setConnection(Port.DOWN, wireInB, true);
        andNAB.setConnection(Port.RIGHT, wireOutNAB, true);
        PrimitivePrototypeNode andANBC = builder.addNode(new PrimitivePrototypeNode(PrimitivePrototypeNode.Type.AND, 3, WireType.SINGLE));
        andANBC.setConnection(Port.UP, wireInA, true);
        andANBC.setConnection(Port.LEFT, wireInNB, true);
        andANBC.setConnection(Port.DOWN, wireInC, true);
        andANBC.setConnection(Port.RIGHT, wireOutANBC, true);
        PrimitivePrototypeNode andBNC = builder.addNode(new PrimitivePrototypeNode(PrimitivePrototypeNode.Type.AND, 2, WireType.SINGLE));
        andBNC.setConnection(Port.UP, wireInB, true);
        andBNC.setConnection(Port.DOWN, wireInNC, true);
        andBNC.setConnection(Port.RIGHT, wireOutBNC, true);
        PrimitivePrototypeNode andNBC = builder.addNode(new PrimitivePrototypeNode(PrimitivePrototypeNode.Type.AND, 2, WireType.SINGLE));
        andNBC.setConnection(Port.UP, wireInNB, true);
        andNBC.setConnection(Port.DOWN, wireInC, true);
        andNBC.setConnection(Port.RIGHT, wireOutNBC, true);

        PrimitivePrototypeNode orA1 = builder.addNode(new PrimitivePrototypeNode(PrimitivePrototypeNode.Type.OR, 3, WireType.SINGLE));
        orA1.setConnection(Port.UP, wireInD, true);
        orA1.setConnection(Port.LEFT, wireInB, true);
        orA1.setConnection(Port.DOWN, wireOutAC, true);
        orA1.setConnection(Port.RIGHT, wireOutAInter, true);
        PrimitivePrototypeNode orA2 = builder.addNode(new PrimitivePrototypeNode(PrimitivePrototypeNode.Type.OR, 2, WireType.SINGLE));
        orA2.setConnection(Port.UP, wireOutAInter, true);
        orA2.setConnection(Port.DOWN, wireOutNANC, true);
        orA2.setConnection(Port.RIGHT, wireOutA, true);
        PrimitivePrototypeNode orB = builder.addNode(new PrimitivePrototypeNode(PrimitivePrototypeNode.Type.OR, 3, WireType.SINGLE));
        orB.setConnection(Port.UP, wireInNC, true);
        orB.setConnection(Port.LEFT, wireOutNANB, true);
        orB.setConnection(Port.DOWN, wireOutAB, true);
        orB.setConnection(Port.RIGHT, wireOutB, true);
        PrimitivePrototypeNode orC = builder.addNode(new PrimitivePrototypeNode(PrimitivePrototypeNode.Type.OR, 3, WireType.SINGLE));
        orC.setConnection(Port.UP, wireInC, true);
        orC.setConnection(Port.LEFT, wireInNB, true);
        orC.setConnection(Port.DOWN, wireInA, true);
        orC.setConnection(Port.RIGHT, wireOutC, true);
        PrimitivePrototypeNode orD1 = builder.addNode(new PrimitivePrototypeNode(PrimitivePrototypeNode.Type.OR, 3, WireType.SINGLE));
        orD1.setConnection(Port.UP, wireInD, true);
        orD1.setConnection(Port.LEFT, wireOutNANC, true);
        orD1.setConnection(Port.DOWN, wireOutBNC, true);
        orD1.setConnection(Port.RIGHT, wireOutDInter, true);
        PrimitivePrototypeNode orD2 = builder.addNode(new PrimitivePrototypeNode(PrimitivePrototypeNode.Type.OR, 3, WireType.SINGLE));
        orD2.setConnection(Port.UP, wireOutDInter, true);
        orD2.setConnection(Port.LEFT, wireOutNAB, true);
        orD2.setConnection(Port.DOWN, wireOutANBC, true);
        orD2.setConnection(Port.RIGHT, wireOutD, true);
        PrimitivePrototypeNode orE = builder.addNode(new PrimitivePrototypeNode(PrimitivePrototypeNode.Type.OR, 2, WireType.SINGLE));
        orE.setConnection(Port.UP, wireOutNANC, true);
        orE.setConnection(Port.DOWN, wireOutNAB, true);
        orE.setConnection(Port.RIGHT, wireOutE, true);
        PrimitivePrototypeNode orF1 = builder.addNode(new PrimitivePrototypeNode(PrimitivePrototypeNode.Type.OR, 3, WireType.SINGLE));
        orF1.setConnection(Port.UP, wireInD, true);
        orF1.setConnection(Port.LEFT, wireOutNBC, true);
        orF1.setConnection(Port.DOWN, wireOutNAC, true);
        orF1.setConnection(Port.RIGHT, wireOutFInter, true);
        PrimitivePrototypeNode orF2 = builder.addNode(new PrimitivePrototypeNode(PrimitivePrototypeNode.Type.OR, 2, WireType.SINGLE));
        orF2.setConnection(Port.UP, wireOutFInter, true);
        orF2.setConnection(Port.DOWN, wireOutNANB, true);
        orF2.setConnection(Port.RIGHT, wireOutF, true);
        PrimitivePrototypeNode orG1 = builder.addNode(new PrimitivePrototypeNode(PrimitivePrototypeNode.Type.OR, 3, WireType.SINGLE));
        orG1.setConnection(Port.UP, wireInD, true);
        orG1.setConnection(Port.LEFT, wireOutNBC, true);
        orG1.setConnection(Port.DOWN, wireOutBNC, true);
        orG1.setConnection(Port.RIGHT, wireOutGInter, true);
        PrimitivePrototypeNode orG2 = builder.addNode(new PrimitivePrototypeNode(PrimitivePrototypeNode.Type.OR, 2, WireType.SINGLE));
        orG2.setConnection(Port.UP, wireOutGInter, true);
        orG2.setConnection(Port.DOWN, wireOutNAB, true);
        orG2.setConnection(Port.RIGHT, wireOutG, true);

        ConverterPrototypeNode packA = builder.addNode(new ConverterPrototypeNode(ConverterPrototypeNode.Type.PACK));
        packA.setBitIndex(0);
        packA.setConnection(Port.LEFT, wireOutA, true);
        packA.setConnection(Port.RIGHT, wireOut, true);
        ConverterPrototypeNode packB = builder.addNode(new ConverterPrototypeNode(ConverterPrototypeNode.Type.PACK));
        packB.setBitIndex(1);
        packB.setConnection(Port.LEFT, wireOutB, true);
        packB.setConnection(Port.RIGHT, wireOut, true);
        ConverterPrototypeNode packC = builder.addNode(new ConverterPrototypeNode(ConverterPrototypeNode.Type.PACK));
        packC.setBitIndex(2);
        packC.setConnection(Port.LEFT, wireOutC, true);
        packC.setConnection(Port.RIGHT, wireOut, true);
        ConverterPrototypeNode packD = builder.addNode(new ConverterPrototypeNode(ConverterPrototypeNode.Type.PACK));
        packD.setBitIndex(3);
        packD.setConnection(Port.LEFT, wireOutD, true);
        packD.setConnection(Port.RIGHT, wireOut, true);
        ConverterPrototypeNode packE = builder.addNode(new ConverterPrototypeNode(ConverterPrototypeNode.Type.PACK));
        packE.setBitIndex(4);
        packE.setConnection(Port.LEFT, wireOutE, true);
        packE.setConnection(Port.RIGHT, wireOut, true);
        ConverterPrototypeNode packF = builder.addNode(new ConverterPrototypeNode(ConverterPrototypeNode.Type.PACK));
        packF.setBitIndex(5);
        packF.setConnection(Port.LEFT, wireOutF, true);
        packF.setConnection(Port.RIGHT, wireOut, true);
        ConverterPrototypeNode packG = builder.addNode(new ConverterPrototypeNode(ConverterPrototypeNode.Type.PACK));
        packG.setBitIndex(6);
        packG.setConnection(Port.LEFT, wireOutG, true);
        packG.setConnection(Port.RIGHT, wireOut, true);

        return builder.build();
    }

    private ComplexTestCircuits() { }
}
