plugins {
    id 'java-library'
    id 'maven-publish'
    id 'net.neoforged.moddev' version '2.0.140'
    id "me.champeau.jmh" version "0.7.3"
}

version = mod_version
group = 'io.github.xfacthd.microredstone'

base {
    archivesName = 'MicroRedstone'
}

java.toolchain.languageVersion = JavaLanguageVersion.of(25)

neoForge {
    version = project.neoforge_version

    validateAccessTransformers = true

    interfaceInjectionData = files('src/main/resources/injected_interfaces.json')

    runs {
        configureEach {
            // systemProperty  'neoforge.logging.markers', 'SCAN,REGISTRIES,REGISTRYDUMP'
            systemProperty 'neoforge.enabledGameTestNamespaces', 'framedblocks'
            systemProperty 'terminal.ansi', 'true'

            logLevel = org.slf4j.event.Level.DEBUG

            sourceSet = project.sourceSets.test
        }

        client {
            client()
            gameDirectory = project.file('run')

            systemProperty('microredstone.compiler_dump.root_dir', file('./run').getAbsolutePath())
            systemProperty('microredstone.compiler_dump.sub_dir', 'runtime')
        }

        server {
            server()
            gameDirectory = project.file('run_server')

            programArgument '--nogui'
        }

        data {
            clientData()
            gameDirectory = project.file('run')

            programArguments.addAll(
                    '--mod', 'microredstone',
                    '--all',
                    '--output', file('src/generated/resources/').getAbsolutePath(),
                    '--existing', file('src/main/resources/').getAbsolutePath()
            )
        }

        gameTestServer {
            type = "gameTestServer"
            gameDirectory = project.file('run_gametest')
        }
    }

    mods {
        microredstone {
            sourceSet(project.sourceSets.main)
            sourceSet(project.sourceSets.test)
        }
    }

    unitTest {
        enable()
        testedMod = mods.microredstone
    }

    addModdingDependenciesTo(project.sourceSets.test)
}

sourceSets {
    main.resources {
        srcDir 'src/generated/resources'
    }

    test {
        java {
            srcDir "src/test/java"
        }
        resources {
            srcDir "src/test/resources"
        }
    }
}

repositories {
    exclusiveContent {
        forRepository {
            maven {
                name = 'CurseMaven'
                url = 'https://www.cursemaven.com'
            }
        }
        filter {
            includeGroup('curse.maven')
        }
    }
    exclusiveContent {
        forRepository {
            maven {
                name = 'Commoble\'s Maven'
                url = 'https://maven.commoble.net'
            }
        }
        filter {
            includeGroup('net.commoble.exmachina')
        }
    }
}

dependencies {
    compileOnly("curse.maven:atlasviewer-633577:${atlasviewer_coord}")
    runtimeOnly("curse.maven:atlasviewer-633577:${atlasviewer_coord}")

    compileOnly("net.commoble.exmachina:exmachina:${exmachina_version}")
    //runtimeOnly("curse.maven:morered-387638:${morered_coord}")

    testImplementation 'org.junit.jupiter:junit-jupiter:5.7.1'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

test {
    useJUnitPlatform()

    systemProperty('microredstone.compiler_dump.root_dir', file('./run').getAbsolutePath())
    systemProperty('microredstone.compiler_dump.sub_dir', 'test')
}

jmh {
    fork = 1
    includeTests = true
    zip64 = true
}

tasks.withType(ProcessResources).configureEach {
    var replaceProperties = [
            minecraft_version: minecraft_version,
            minecraft_version_range: minecraft_version_range,
            neoforge_version: neoforge_version,
            neoforge_version_range: neoforge_version_range,
            mod_version: mod_version,
            exmachina_version: exmachina_version
    ]
    inputs.properties replaceProperties

    filesMatching(['META-INF/neoforge.mods.toml']) {
        expand replaceProperties
    }
}

publishing {
    publications {
        register ('mavenJava', MavenPublication) {
            from components.java
        }
    }
    repositories {
        maven {
            url = "file://${project.projectDir}/mcmodsrepo"
        }
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8' // Use the UTF-8 charset for Java compilation
    options.compilerArgs << "-Xmaxerrs" << "10000"
}
