# Sets default memory used for Gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

# Mod properties
minecraft_version=26.1
minecraft_version_range=[26.1,26.2)
neoforge_version=26.1.0.1-beta
neoforge_version_range=[26.1.0.1-beta,)
mod_version=1.0.0

# Dependency properties
atlasviewer_coord=7806148
atlasviewer_version=16.0.0
exmachina_version=21.9.2
morered_coord=7100518
morered_version=21.10.0
