# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

# Mod properties
minecraft_version=1.21.6
minecraft_version_range=[1.21.6,)
neoforge_version=21.6.4-beta
neoforge_version_range=[21.6.4-beta,)
mod_version=1.0.0
parchment_minecraft_version=1.21.5
parchment_mappings_version=2025.06.01

# Dependency properties
atlasviewer_coord=6663662
atlasviewer_version=13.0.0
